
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Communications = lazy(() => import("./pages/Communications.tsx"));
const CompanyRegistration = lazy(() => import("./pages/CompanyRegistration.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const EmployeeLogin = lazy(() => import("./pages/EmployeeLogin.tsx"));
const EmployeeManagement = lazy(() => import("./pages/EmployeeManagement.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Unauthorized = lazy(() => import("./pages/Unauthorized.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/communications", element: <Communications />},
	{ path: "/company-registration", element: <CompanyRegistration />},
	{ path: "/companyregistration", element: <CompanyRegistration />},
	{ path: "/contact", element: <Contact />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/employee-login", element: <EmployeeLogin />},
	{ path: "/employeelogin", element: <EmployeeLogin />},
	{ path: "/employee-management", element: <EmployeeManagement />},
	{ path: "/employeemanagement", element: <EmployeeManagement />},
	{ path: "/login", element: <Login />},
	{ path: "/unauthorized", element: <Unauthorized />},

];
